import pandas as pd

def get_cumulative_df(transactions: pd.DataFrame, applications: pd.DataFrame, balances: pd.DataFrame,
                      year=None, month=None, day=None) -> pd.DataFrame:
    """Returns a hour sampled df with the cumulative costs, balances and patrimony per column"""
    pass

def get_revenue_df(applications: pd.DataFrame) -> pd.DataFrame:
    """Returns a hour sampled df with the cumulative revenue generated by the applications"""
    pass